#
#开发模式 配置文件
#
#



#开启自定义插件支持
plugins:
  es: true
  resid: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.127.25:3306/baseproject
    username: root
    password: admin
    type:  com.alibaba.druid.pool.DruidDataSource  #默认使用TomcatJDBD DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data

  redis:  #单机版
    port: 6379
    host: 127.0.0.1
    database: 0


  mail:
    host: smtp.qq.com
    username: 694381173@qq.com
    password: 
    default-encoding: utf-8
    properties:
      mail.smtp:
        auth: trun
        starttls.enable: true
        starttls.required: true

logging:

  path: #/var/logs          # 在/var/logs目录下生成spring.log文件
  file: #/var/logs/test.log # 在/var/logs目录下生成test.log文件
  config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
  level: # 配置spring web日志级别
    root : info
    org.springframework.web: error
    com.example.baseproject.service: info






