#开启自定义插件支持
plugins:
  es: false
  resid: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.127.25:3306/baseproject
    username: root
    password: 
    type:  com.alibaba.druid.pool.DruidDataSource  #默认使用TomcatJDBD DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data

  redis:  #单机版
    port: 6379
    host: 127.0.0.1
    database: 0


  mail:
    host: smtp.qq.com
    username: 694381173@qq.com
    password: 
    default-encoding: utf-8
    properties:
      mail.smtp:
        auth: trun
        starttls.enable: true
        starttls.required: true



