spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    type:  com.alibaba.druid.pool.DruidDataSource  #默认使用TomcatJDBD DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    elasticsearch:
      cluster-name:
      cluster-nodes:
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data

  redis:  #单机版
    port:
    host:
    database: 0


  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: utf-8
    properties:
      mail.smtp:
        auth: trun
        starttls.enable: true
        starttls.required: true




