#
#开发模式 配置文件
#
#

#开启自定义插件支持
plugins:
  es: false
  resid: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.127.25:3306/baseproject
    username: test
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  #默认使用TomcatJDBD DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 39.106.127.25:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data

  redis:  #单机版
    port: 6379
    host: 39.106.127.25
    database: 0


  mail:
    host: smtp.qq.com
    username: 694381173@qq.com
    password: 
    default-encoding: utf-8
    properties:
      mail.smtp:
        auth: trun
        starttls.enable: true
        starttls.required: true

logging:

  path: #/var/logs          # 在/var/logs目录下生成spring.log文件
  file: #/var/logs/test.log # 在/var/logs目录下生成test.log文件
  config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
  level: # 配置spring web日志级别
    root : info
    org.springframework.web: info
    com.example.baseproject.service: info

sdk:
  alipay:
    dev: true #默认false,为true表示使用沙箱环境
    sign-type: RSA2 #签名算法
    app-id: 2016091200494044
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/yYXU6Wzkk2dwbfC4IvLGqMgz/xHbdUULOSRs+MB1SR3DU1Pc6OMssuCglsGbi88E3JCd5I/yrh9dsPamDqlT4hZVwkI50oYMGKzU7loLy8WZa3pYuGVDsWRABMDzQDy2BEDvov6WWj6T6piysVwnNMwdqqB0cG/45JPhqDevBSWFT60chLH0UpEdLxt6gCXcTKsRZe0ZVB18TIY/qNZOr/PuVxzmrcI33DR5ptkrc+Fcx64UDZwkL/SBU+t/e96j0LC2ONOmGr7arHqxzbApubxE5/QfFeUGMY/4cAaMVVH/GyOJeWmhNmHv4EfLBxf66ZcVlEZb46+QMQXwD2zdAgMBAAECggEAE/GB0D0hzLcjV4anNI61zkC46OdKVRbhwiQEDKzlXozm4mvk2aECFqDXSPvEUEd+lJPXGgQtj9/ZdSW00FnP8+Ab0Hkt59Njixh5yH6ssHNVLfoGM/mg1iQ5N4sHAYSZi5fvpLu/W6UwwrLvhA17drw/yYn3u4QBsNEcK6gRekqRm4Im0b45OkAKlVR3J91pshuRcUGDpsmO85E1sKC46lblGatUgilIUCs0cVsI3q2ERHEF/e16oByD2UrGLlTQ7RZWTfC6ckXcAQn71IQl4z1wQpuZXx156LFMNvertM8LZw5F+nkqkc1lEoXbWaHU1VXTfIQ+cbNaOLwBuxp74QKBgQDk/U44dc2k6/6nadnAR5V1b0KwZzMWSnV8D6H6vSJe6ih6aF5PeEyAO8CwzQgK1YwOOn+EzNaPsUdmkhPjmTp2/eiOMPTtr0op5qH7ABBIXlE9rroEZoyk7fVAWhshgPO1VmYAJLKYPhrmQi8UaxLGhu0xyR5KKsAGTePdj9Mo6QKBgQDWaNYhwEHQbHa9vIjp5JL0qRgexUi0doxf8gNWSZmajOr3OsCP6406RGYrQ8K/GGYBQ6pgFhA5WnyFc8pv6SXl8UnJe6XGrFBAjOPjQhmSpAdVrW/cwvwVTX5tbzr815bx9qpbJgBdWj5Y70gtC7DpF+3KOIZAfFm4Dlduzf1r1QKBgCLrZeRCQqvluR26jJQ/1lDkOJ1B/45kqGnU0HS2Jummd6nDBK7Fv5TGh+nuOk28pvD8hrmvqwCanjLMD/BjS4Ed0zrryE3+ryaYnxbxuYnvqB/p50AIi2YTS5UWqJCBY6jBlihrcDi7L8rxSNCqS2Cu7rjq3I2e202azybYafERAoGBANMf9kLTwrrOIvpgLN1LUx2RaAvcrePtm/paH8kWvib+PdxmQPk2tCE8+vH9TkXHa6IxFBJ7h0xCer0aMKuUA9pxhvvcQnfoczmswjWkf/PyirpmBvF2Gq2LWkO+NHKGg78M6eDJAbDqzNvb+tFIYtKT2nW2xRO4nsvra1LTiYhlAoGBAN6Aws7SYCliM35Td8yIcGHonMg4EB6XzmlY6UKtoV7We+B4MM3jbuj2kmhVlpYhIesa4pkWMwdtbCM67b11RNNn2SMz3O6Z0Ro0IAOKF6Y6Zp+rqa+8wf4WZ3E4StGAh5+Mt1FYe/6kebkSQQjNiXBGvP4c17+4uOPjAGoHJuRH
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtZm0BejP168Lt2jmRpfba/cpxuuiS2ZvkpHRYVLgHa2Mr3spfcL+xJBJWzU3H0tDB4azKXII8h8JxbQaTN7aMZA8uGMreBWDMmjdFRIaURKZP3j0YK6nfB9CxAQ0wv57zjXxTnVTjhV+h2rR9Yq/1DteoIZ03DJOc45Fos8nuv/eAuj7g6VDkzUKULMJzSskxk9N3Gsu2qgrQK3upeQK9deWqw/da8ZK1G/5CihmZPG4+3H8/SfaE8icu0k+jt1b7uDujtcLKk8yXWrVo7LygOmr4RmqgbahS5sbDW1/014MaGQcs1MOLHYrJDbApWUM1lBYFizZAcVLtsJElCRSPQIDAQAB








