#
#开发模式 配置文件
#
#

#开启自定义插件支持
plugins:
  es: false
  resid: false

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.127.25:3306/baseproject
    username: test
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource  #默认使用TomcatJDBD DataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 39.106.127.25:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data

  redis:  #单机版
#    port: 6379
#    host: 39.106.127.25
#    database: 0
    pool: #集群版
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    sentinel:
      master: redis
      nodes: 39.106.127.25:26379
  mail:
    host: smtp.qq.com
    username: 694381173@qq.com
    password: 
    default-encoding: utf-8
    properties:
      mail.smtp:
        auth: trun
        starttls.enable: true
        starttls.required: true

logging:

  path: #/var/logs          # 在/var/logs目录下生成spring.log文件
  file: #/var/logs/test.log # 在/var/logs目录下生成test.log文件
  config: # 日志配置文件,Spring Boot默认使用classpath路径下的日志配置文件,如:logback.xml
  level: # 配置spring web日志级别
    root : info
    org.springframework.web: error
    com.example.baseproject.service: info
management:
  security:
  enabled: false
  port: 8088 #管理端口
  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
  actuator:
    enabled: true
info:
   app:
   name: spring-boot-actuator
   version: 1.0.0










